trigger:
  - "*"

pool:
  vmImage: "ubuntu-20.04"

#Set true/false for every test to pass/fail
variables:
  TEST1: "50"
  TEST2: "50"
  TEST3: "50"
  TEST4: "50"

steps:
  - script: dotnet test --logger "junit;verbosity=detailed"
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: "**/*.xml"
