trigger:
  - "*"

pool:
  vmImage: "ubuntu-20.04"

#Set number between 0-100 for test success rate
variables:
  TEST1: "50"
  TEST2: "50"
  TEST3: "50"
  TEST4: "50"

steps:
  - script: dotnet test -l:"trx;LogFileName=testresult.xml"
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: "**/*.xml"
